
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

# from ...modules.downloader import downloader
import asyncio
from modules.downloader import downloader
from pathlib import Path

from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = r"D:\Documentos\programación\python\youtube_downloader\build\assets\frame0"
print(OUTPUT_PATH)
# FRAME_0 = str(OUTPUT_PATH)+"\\build\\assets\\frame0"
ASSETS_PATH = OUTPUT_PATH / Path(OUTPUT_PATH)
print(ASSETS_PATH)
print(r"D:\Documentos\programación\python\youtube_downloader\build\assets\frame0")


descargando = ""

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def msg_video():
    global descargando
    descargando = "descargando video..."
    canvas.itemconfig(tagOrId=descargando_msg, text=descargando)

def msg_audio():
    global descargando
    descargando = "descargando audio..."
    canvas.itemconfig(tagOrId=descargando_msg, text=descargando)

def handler_download_video():
    try:
        downloader.download_video(entry_1.get())
    except Exception as e:
        print("no ha colocado ningún link uwu")
        print(e)

def handler_download_audio():
    global descargando
    descargando = "descargando audio..."
    try:
        downloader.download_audio(entry_1.get())
    except Exception as e:
        print(e)

def on_button_click_video():
    def descargando_finished():
        global descargando
        descargando = ""

    msg_video()  # Primero ejecuta msg_video()

    # Programa la ejecución de handler_download_video() después de 2000 milisegundos (2 segundos)
    window.after(2000, handler_download_video)
    window.after(2000, descargando_finished)

def on_button_click_audio():
    def descargando_finished():
        global descargando
        descargando = ""
    msg_audio()  # Primero ejecuta msg_audio()

    # Programa la ejecución de handler_download_audio() después de 2000 milisegundos (2 segundos)
    window.after(2000, handler_download_audio)
    window.after(2000, descargando_finished)


window = Tk()

window.geometry("1296x720")
window.configure(bg = "#F0F0F0")


canvas = Canvas(
    window,
    bg = "#F0F0F0",
    height = 720,
    width = 1296,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    34.0,
    360.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=0.0,
    y=0.0,
    width=68.0,
    height=52.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=0.0,
    y=52.0,
    width=68.0,
    height=52.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=0.0,
    y=104.0,
    width=68.0,
    height=52.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=0.0,
    y=616.0,
    width=68.0,
    height=52.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=0.0,
    y=668.0,
    width=68.0,
    height=52.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    648.0,
    173.0,
    image=image_image_2
)

canvas.create_text(
    378.0,
    293.0,
    anchor="nw",
    text="Ingresar URL:",
    fill="#000000",
    font=("Inter", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    648.0,
    360.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Inter", 20 * -1)
)
entry_1.place(
    x=388.0,
    y=328.0,
    width=520.0,
    height=63.0
)

descargando_msg = canvas.create_text(
    568.4,
    547.0,
    anchor="nw",
    text=descargando,
    fill="#000000",
    font=("Inter", 20 * -1)
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=on_button_click_video,
    relief="flat"
)
button_6.place(
    x=431.0,
    y=447.0,
    width=190.0,
    height=51.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=on_button_click_audio,
    relief="flat"
)
button_7.place(
    x=678.0,
    y=447.0,
    width=190.0,
    height=51.0
)



window.resizable(False, False)
window.mainloop()

if __name__ == "__main__":
    pass